# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip3 install --upgrade pip3
        pip3 install flake8 pytest
        pip3 install flask 
        pip3 install kubernetes
        pip3 install openshift
        pip3 install crontabs
   
    - name: Test with pytest
      run: |
        pytest tests/get_cumulative_information_test.py
